name: Bug Report
description: Report a bug in PrompTTY
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: "Pre-submit Checks"
      options:
        - label: "I have searched existing issues and this is not a duplicate"
          required: true
  - type: textarea
    id: "describe-the-bug"
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: "to-reproduce"
    attributes:
      label: "To reproduce"
      placeholder: "1. Go to '...' 2. Click on '...' 3. See error '...'"
    validations:
      required: true
  - type: textarea
    id: "expected-behavior"
    attributes:
      label: "Expected behavior"
    validations:
      required: false
  - type: dropdown
    id: "os"
    attributes:
      label: "Operating system"
      options:
        - macOS
        - Linux
    validations:
      required: true
  - type: input
    id: "os-version"
    attributes:
      label: "OS version"
      description: "For example: macOS 15.6, Debian 12"
    validations:
      required: true
  - type: textarea
    id: "screenshots-logs"
    attributes:
      label: "Screenshots, videos, and logs"
    validations:
      required: false
